"""Initial migration

Revision ID: 00c13b2e1e65
Revises:
Create Date: 2025-10-27 04:07:31.118354

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "00c13b2e1e65"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		"analysis_history",
		sa.Column("id", sa.UUID(), nullable=False),
		sa.Column("contract_id", sa.UUID(), nullable=False),
		sa.Column("analysis_type", sa.String(length=100), nullable=False),
		sa.Column("status", sa.String(length=50), nullable=False),
		sa.Column("risk_level", sa.String(length=50), nullable=True),
		sa.Column("model_used", sa.String(length=100), nullable=True),
		sa.Column("processing_time", sa.Numeric(precision=10, scale=3), nullable=True),
		sa.Column("total_cost", sa.Numeric(precision=10, scale=6), nullable=True),
		sa.Column("total_tokens", sa.Integer(), nullable=True),
		sa.Column("analysis_results", sa.JSON(), nullable=True),
		sa.Column("analysis_metadata", sa.JSON(), nullable=True),
		sa.Column("created_at", sa.DateTime(), nullable=False),
		sa.Column("updated_at", sa.DateTime(), nullable=True),
		sa.Column("completed_at", sa.DateTime(), nullable=True),
		sa.Column("deleted_at", sa.DateTime(), nullable=True),
		sa.PrimaryKeyConstraint("id"),
	)
	op.create_table(
		"analytics",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("user_id", sa.Integer(), nullable=True),
		sa.Column("type", sa.String(), nullable=False),
		sa.Column("data", sa.JSON(), nullable=False),
		sa.Column("generated_at", sa.DateTime(), nullable=False),
		sa.PrimaryKeyConstraint("id"),
	)
	op.create_index(op.f("ix_analytics_id"), "analytics", ["id"], unique=False)
	op.create_index(op.f("ix_analytics_type"), "analytics", ["type"], unique=False)
	op.create_index(op.f("ix_analytics_user_id"), "analytics", ["user_id"], unique=False)
	op.create_table(
		"contract_analyses",
		sa.Column("id", sa.UUID(), nullable=False),
		sa.Column("contract_id", sa.UUID(), nullable=False),
		sa.Column("analysis_type", sa.String(length=100), nullable=False),
		sa.Column("status", sa.String(length=50), nullable=False),
		sa.Column("results", sa.JSON(), nullable=True),
		sa.Column("created_at", sa.DateTime(), nullable=False),
		sa.Column("updated_at", sa.DateTime(), nullable=True),
		sa.PrimaryKeyConstraint("id"),
	)
	op.create_table(
		"help_articles",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("title", sa.String(length=255), nullable=False),
		sa.Column("slug", sa.String(length=255), nullable=False),
		sa.Column("content", sa.Text(), nullable=False),
		sa.Column("excerpt", sa.String(length=500), nullable=True),
		sa.Column("category", sa.String(length=100), nullable=False),
		sa.Column("tags", sa.JSON(), nullable=True),
		sa.Column("meta_description", sa.String(length=500), nullable=True),
		sa.Column("search_keywords", sa.JSON(), nullable=True),
		sa.Column("is_published", sa.Boolean(), nullable=True),
		sa.Column("published_at", sa.DateTime(), nullable=True),
		sa.Column("view_count", sa.Integer(), nullable=True),
		sa.Column("helpful_votes", sa.Integer(), nullable=True),
		sa.Column("unhelpful_votes", sa.Integer(), nullable=True),
		sa.Column("created_at", sa.DateTime(), nullable=True),
		sa.Column("updated_at", sa.DateTime(), nullable=True),
		sa.PrimaryKeyConstraint("id"),
	)
	op.create_index(op.f("ix_help_articles_category"), "help_articles", ["category"], unique=False)
	op.create_index(op.f("ix_help_articles_created_at"), "help_articles", ["created_at"], unique=False)
	op.create_index(op.f("ix_help_articles_id"), "help_articles", ["id"], unique=False)
	op.create_index(op.f("ix_help_articles_is_published"), "help_articles", ["is_published"], unique=False)
	op.create_index(op.f("ix_help_articles_slug"), "help_articles", ["slug"], unique=True)
	op.create_table(
		"users",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("username", sa.String(), nullable=False),
		sa.Column("email", sa.String(), nullable=False),
		sa.Column("hashed_password", sa.String(), nullable=False),
		sa.Column("skills", sa.JSON(), nullable=True),
		sa.Column("preferred_locations", sa.JSON(), nullable=True),
		sa.Column("experience_level", sa.String(), nullable=True),
		sa.Column("daily_application_goal", sa.Integer(), nullable=True),
		sa.Column("is_admin", sa.Boolean(), nullable=False),
		sa.Column("oauth_provider", sa.String(), nullable=True),
		sa.Column("oauth_id", sa.String(), nullable=True),
		sa.Column("profile_picture_url", sa.String(), nullable=True),
		sa.Column("created_at", sa.DateTime(), nullable=True),
		sa.Column("updated_at", sa.DateTime(), nullable=True),
		sa.PrimaryKeyConstraint("id"),
	)
	op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
	op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
	op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
	op.create_table(
		"agent_executions",
		sa.Column("id", sa.UUID(), nullable=False),
		sa.Column("analysis_id", sa.UUID(), nullable=False),
		sa.Column("agent_name", sa.String(length=100), nullable=False),
		sa.Column("agent_type", sa.String(length=50), nullable=False),
		sa.Column("agent_id", sa.String(length=100), nullable=True),
		sa.Column("status", sa.String(length=50), nullable=False),
		sa.Column("llm_provider", sa.String(length=50), nullable=True),
		sa.Column("model_name", sa.String(length=100), nullable=True),
		sa.Column("provider", sa.String(length=50), nullable=True),
		sa.Column("started_at", sa.DateTime(), nullable=False),
		sa.Column("completed_at", sa.DateTime(), nullable=True),
		sa.Column("execution_time", sa.Numeric(precision=10, scale=3), nullable=True),
		sa.Column("duration", sa.Numeric(precision=10, scale=3), nullable=True),
		sa.Column("cost", sa.Numeric(precision=10, scale=6), nullable=True),
		sa.Column("token_usage", sa.Integer(), nullable=True),
		sa.Column("input_data", sa.JSON(), nullable=True),
		sa.Column("output_data", sa.JSON(), nullable=True),
		sa.Column("error_message", sa.Text(), nullable=True),
		sa.Column("error_type", sa.String(length=100), nullable=True),
		sa.Column("retry_count", sa.Integer(), nullable=True),
		sa.Column("fallback_used", sa.Boolean(), nullable=True),
		sa.Column("circuit_breaker_triggered", sa.Boolean(), nullable=True),
		sa.Column("execution_metadata", sa.JSON(), nullable=True),
		sa.Column("created_at", sa.DateTime(), nullable=False),
		sa.Column("updated_at", sa.DateTime(), nullable=True),
		sa.ForeignKeyConstraint(
			["analysis_id"],
			["analysis_history.id"],
		),
		sa.PrimaryKeyConstraint("id"),
	)
	op.create_table(
		"feedback",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("user_id", sa.Integer(), nullable=False),
		sa.Column(
			"type",
			sa.Enum(
				"JOB_RECOMMENDATION",
				"SKILL_GAP_SUGGESTION",
				"CONTENT_GENERATION",
				"INTERVIEW_PRACTICE",
				"GENERAL",
				"BUG_REPORT",
				"FEATURE_REQUEST",
				name="feedbacktype",
			),
			nullable=False,
		),
		sa.Column("priority", sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", name="feedbackpriority"), nullable=True),
		sa.Column("status", sa.Enum("OPEN", "IN_PROGRESS", "RESOLVED", "CLOSED", name="feedbackstatus"), nullable=True),
		sa.Column("title", sa.String(length=255), nullable=False),
		sa.Column("description", sa.Text(), nullable=False),
		sa.Column("page_url", sa.String(length=500), nullable=True),
		sa.Column("user_agent", sa.String(length=500), nullable=True),
		sa.Column("screen_resolution", sa.String(length=50), nullable=True),
		sa.Column("browser_info", sa.JSON(), nullable=True),
		sa.Column("extra_data", sa.JSON(), nullable=True),
		sa.Column("admin_response", sa.Text(), nullable=True),
		sa.Column("admin_notes", sa.Text(), nullable=True),
		sa.Column("created_at", sa.DateTime(), nullable=True),
		sa.Column("updated_at", sa.DateTime(), nullable=True),
		sa.Column("resolved_at", sa.DateTime(), nullable=True),
		sa.ForeignKeyConstraint(
			["user_id"],
			["users.id"],
		),
		sa.PrimaryKeyConstraint("id"),
	)
	op.create_index(op.f("ix_feedback_created_at"), "feedback", ["created_at"], unique=False)
	op.create_index(op.f("ix_feedback_id"), "feedback", ["id"], unique=False)
	op.create_index(op.f("ix_feedback_status"), "feedback", ["status"], unique=False)
	op.create_index(op.f("ix_feedback_type"), "feedback", ["type"], unique=False)
	op.create_index(op.f("ix_feedback_user_id"), "feedback", ["user_id"], unique=False)
	op.create_table(
		"help_article_votes",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("article_id", sa.Integer(), nullable=False),
		sa.Column("user_id", sa.Integer(), nullable=False),
		sa.Column("is_helpful", sa.Boolean(), nullable=False),
		sa.Column("created_at", sa.DateTime(), nullable=True),
		sa.ForeignKeyConstraint(
			["article_id"],
			["help_articles.id"],
		),
		sa.ForeignKeyConstraint(
			["user_id"],
			["users.id"],
		),
		sa.PrimaryKeyConstraint("id"),
	)
	op.create_index(op.f("ix_help_article_votes_article_id"), "help_article_votes", ["article_id"], unique=False)
	op.create_index(op.f("ix_help_article_votes_id"), "help_article_votes", ["id"], unique=False)
	op.create_index(op.f("ix_help_article_votes_user_id"), "help_article_votes", ["user_id"], unique=False)
	op.create_table(
		"jobs",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("user_id", sa.Integer(), nullable=False),
		sa.Column("company", sa.String(), nullable=False),
		sa.Column("title", sa.String(), nullable=False),
		sa.Column("location", sa.String(), nullable=True),
		sa.Column("description", sa.Text(), nullable=True),
		sa.Column("requirements", sa.Text(), nullable=True),
		sa.Column("salary_range", sa.String(), nullable=True),
		sa.Column("salary_min", sa.Integer(), nullable=True),
		sa.Column("salary_max", sa.Integer(), nullable=True),
		sa.Column("job_type", sa.String(), nullable=True),
		sa.Column("remote_option", sa.String(), nullable=True),
		sa.Column("tech_stack", sa.JSON(), nullable=True),
		sa.Column("responsibilities", sa.Text(), nullable=True),
		sa.Column("documents_required", sa.JSON(), nullable=True),
		sa.Column("application_url", sa.String(), nullable=True),
		sa.Column("source_url", sa.String(), nullable=True),
		sa.Column("source", sa.String(), nullable=True),
		sa.Column("status", sa.String(), nullable=True),
		sa.Column("notes", sa.Text(), nullable=True),
		sa.Column("date_applied", sa.DateTime(), nullable=True),
		sa.Column("created_at", sa.DateTime(), nullable=True),
		sa.Column("updated_at", sa.DateTime(), nullable=True),
		sa.Column("currency", sa.String(), nullable=True),
		sa.ForeignKeyConstraint(
			["user_id"],
			["users.id"],
		),
		sa.PrimaryKeyConstraint("id"),
	)
	op.create_index(op.f("ix_jobs_company"), "jobs", ["company"], unique=False)
	op.create_index(op.f("ix_jobs_created_at"), "jobs", ["created_at"], unique=False)
	op.create_index(op.f("ix_jobs_id"), "jobs", ["id"], unique=False)
	op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
	op.create_index(op.f("ix_jobs_title"), "jobs", ["title"], unique=False)
	op.create_index(op.f("ix_jobs_user_id"), "jobs", ["user_id"], unique=False)
	op.create_table(
		"onboarding_progress",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("user_id", sa.Integer(), nullable=False),
		sa.Column("steps_completed", sa.JSON(), nullable=True),
		sa.Column("current_step", sa.String(), nullable=True),
		sa.Column("tutorials_completed", sa.JSON(), nullable=True),
		sa.Column("features_discovered", sa.JSON(), nullable=True),
		sa.Column("help_topics_viewed", sa.JSON(), nullable=True),
		sa.Column("show_tooltips", sa.Boolean(), nullable=True),
		sa.Column("show_feature_highlights", sa.Boolean(), nullable=True),
		sa.Column("onboarding_completed", sa.Boolean(), nullable=True),
		sa.Column("created_at", sa.DateTime(), nullable=True),
		sa.Column("updated_at", sa.DateTime(), nullable=True),
		sa.Column("completed_at", sa.DateTime(), nullable=True),
		sa.ForeignKeyConstraint(
			["user_id"],
			["users.id"],
		),
		sa.PrimaryKeyConstraint("id"),
	)
	op.create_index(op.f("ix_onboarding_progress_id"), "onboarding_progress", ["id"], unique=False)
	op.create_index(op.f("ix_onboarding_progress_user_id"), "onboarding_progress", ["user_id"], unique=True)
	op.create_table(
		"resume_uploads",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("user_id", sa.Integer(), nullable=False),
		sa.Column("filename", sa.String(), nullable=False),
		sa.Column("file_path", sa.String(), nullable=False),
		sa.Column("file_size", sa.Integer(), nullable=False),
		sa.Column("file_type", sa.String(), nullable=False),
		sa.Column("parsing_status", sa.String(), nullable=True),
		sa.Column("parsed_data", sa.JSON(), nullable=True),
		sa.Column("extracted_skills", sa.JSON(), nullable=True),
		sa.Column("extracted_experience", sa.String(), nullable=True),
		sa.Column("extracted_contact_info", sa.JSON(), nullable=True),
		sa.Column("parsing_error", sa.Text(), nullable=True),
		sa.Column("created_at", sa.DateTime(), nullable=True),
		sa.Column("updated_at", sa.DateTime(), nullable=True),
		sa.ForeignKeyConstraint(
			["user_id"],
			["users.id"],
		),
		sa.PrimaryKeyConstraint("id"),
	)
	op.create_index(op.f("ix_resume_uploads_id"), "resume_uploads", ["id"], unique=False)
	op.create_table(
		"user_job_preferences",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("user_id", sa.Integer(), nullable=False),
		sa.Column("preferred_sources", sa.JSON(), nullable=True),
		sa.Column("disabled_sources", sa.JSON(), nullable=True),
		sa.Column("source_priorities", sa.JSON(), nullable=True),
		sa.Column("auto_scraping_enabled", sa.Boolean(), nullable=True),
		sa.Column("max_jobs_per_source", sa.Integer(), nullable=True),
		sa.Column("min_quality_threshold", sa.Float(), nullable=True),
		sa.Column("notify_on_high_match", sa.Boolean(), nullable=True),
		sa.Column("notify_on_new_sources", sa.Boolean(), nullable=True),
		sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
		sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
		sa.ForeignKeyConstraint(
			["user_id"],
			["users.id"],
		),
		sa.PrimaryKeyConstraint("id"),
	)
	op.create_index(op.f("ix_user_job_preferences_id"), "user_job_preferences", ["id"], unique=False)
	op.create_index(op.f("ix_user_job_preferences_user_id"), "user_job_preferences", ["user_id"], unique=False)
	op.create_table(
		"applications",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("user_id", sa.Integer(), nullable=False),
		sa.Column("job_id", sa.Integer(), nullable=False),
		sa.Column("status", sa.String(), nullable=True),
		sa.Column("applied_date", sa.Date(), nullable=True),
		sa.Column("response_date", sa.Date(), nullable=True),
		sa.Column("interview_date", sa.DateTime(), nullable=True),
		sa.Column("offer_date", sa.Date(), nullable=True),
		sa.Column("notes", sa.Text(), nullable=True),
		sa.Column("interview_feedback", sa.JSON(), nullable=True),
		sa.Column("follow_up_date", sa.Date(), nullable=True),
		sa.Column("created_at", sa.DateTime(), nullable=True),
		sa.Column("updated_at", sa.DateTime(), nullable=True),
		sa.ForeignKeyConstraint(
			["job_id"],
			["jobs.id"],
		),
		sa.ForeignKeyConstraint(
			["user_id"],
			["users.id"],
		),
		sa.PrimaryKeyConstraint("id"),
	)
	op.create_index(op.f("ix_applications_created_at"), "applications", ["created_at"], unique=False)
	op.create_index(op.f("ix_applications_id"), "applications", ["id"], unique=False)
	op.create_index(op.f("ix_applications_job_id"), "applications", ["job_id"], unique=False)
	op.create_index(op.f("ix_applications_status"), "applications", ["status"], unique=False)
	op.create_index(op.f("ix_applications_user_id"), "applications", ["user_id"], unique=False)
	op.create_table(
		"content_generations",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("user_id", sa.Integer(), nullable=False),
		sa.Column("job_id", sa.Integer(), nullable=True),
		sa.Column("content_type", sa.String(), nullable=False),
		sa.Column("generated_content", sa.Text(), nullable=False),
		sa.Column("user_modifications", sa.Text(), nullable=True),
		sa.Column("generation_prompt", sa.Text(), nullable=True),
		sa.Column("tone", sa.String(), nullable=True),
		sa.Column("template_used", sa.String(), nullable=True),
		sa.Column("status", sa.String(), nullable=True),
		sa.Column("created_at", sa.DateTime(), nullable=True),
		sa.Column("updated_at", sa.DateTime(), nullable=True),
		sa.ForeignKeyConstraint(
			["job_id"],
			["jobs.id"],
		),
		sa.ForeignKeyConstraint(
			["user_id"],
			["users.id"],
		),
		sa.PrimaryKeyConstraint("id"),
	)
	op.create_index(op.f("ix_content_generations_id"), "content_generations", ["id"], unique=False)
	op.create_table(
		"feedback_votes",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("feedback_id", sa.Integer(), nullable=False),
		sa.Column("user_id", sa.Integer(), nullable=False),
		sa.Column("vote", sa.Integer(), nullable=False),
		sa.Column("created_at", sa.DateTime(), nullable=True),
		sa.ForeignKeyConstraint(
			["feedback_id"],
			["feedback.id"],
		),
		sa.ForeignKeyConstraint(
			["user_id"],
			["users.id"],
		),
		sa.PrimaryKeyConstraint("id"),
	)
	op.create_index(op.f("ix_feedback_votes_feedback_id"), "feedback_votes", ["feedback_id"], unique=False)
	op.create_index(op.f("ix_feedback_votes_id"), "feedback_votes", ["id"], unique=False)
	op.create_index(op.f("ix_feedback_votes_user_id"), "feedback_votes", ["user_id"], unique=False)
	op.create_table(
		"interview_sessions",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("user_id", sa.Integer(), nullable=False),
		sa.Column("job_id", sa.Integer(), nullable=True),
		sa.Column("interview_type", sa.Enum("behavioral", "technical", "general", name="interviewtype"), nullable=False),
		sa.Column("status", sa.Enum("started", "in_progress", "completed", "cancelled", name="interviewstatus"), nullable=True),
		sa.Column("started_at", sa.DateTime(), nullable=True),
		sa.Column("completed_at", sa.DateTime(), nullable=True),
		sa.Column("feedback", sa.Text(), nullable=True),
		sa.Column("score", sa.Float(), nullable=True),
		sa.Column("created_at", sa.DateTime(), nullable=True),
		sa.Column("updated_at", sa.DateTime(), nullable=True),
		sa.ForeignKeyConstraint(
			["job_id"],
			["jobs.id"],
		),
		sa.ForeignKeyConstraint(
			["user_id"],
			["users.id"],
		),
		sa.PrimaryKeyConstraint("id"),
	)
	op.create_index(op.f("ix_interview_sessions_created_at"), "interview_sessions", ["created_at"], unique=False)
	op.create_index(op.f("ix_interview_sessions_id"), "interview_sessions", ["id"], unique=False)
	op.create_index(op.f("ix_interview_sessions_job_id"), "interview_sessions", ["job_id"], unique=False)
	op.create_index(op.f("ix_interview_sessions_status"), "interview_sessions", ["status"], unique=False)
	op.create_index(op.f("ix_interview_sessions_user_id"), "interview_sessions", ["user_id"], unique=False)
	op.create_table(
		"job_recommendation_feedback",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("user_id", sa.Integer(), nullable=False),
		sa.Column("job_id", sa.Integer(), nullable=False),
		sa.Column("is_helpful", sa.Boolean(), nullable=False),
		sa.Column("match_score", sa.Integer(), nullable=True),
		sa.Column("user_skills_at_time", sa.JSON(), nullable=True),
		sa.Column("user_experience_level", sa.String(), nullable=True),
		sa.Column("user_preferred_locations", sa.JSON(), nullable=True),
		sa.Column("job_tech_stack", sa.JSON(), nullable=True),
		sa.Column("job_location", sa.String(), nullable=True),
		sa.Column("comment", sa.Text(), nullable=True),
		sa.Column("recommendation_context", sa.JSON(), nullable=True),
		sa.Column("created_at", sa.DateTime(), nullable=True),
		sa.Column("updated_at", sa.DateTime(), nullable=True),
		sa.ForeignKeyConstraint(
			["job_id"],
			["jobs.id"],
		),
		sa.ForeignKeyConstraint(
			["user_id"],
			["users.id"],
		),
		sa.PrimaryKeyConstraint("id"),
	)
	op.create_index(op.f("ix_job_recommendation_feedback_created_at"), "job_recommendation_feedback", ["created_at"], unique=False)
	op.create_index(op.f("ix_job_recommendation_feedback_id"), "job_recommendation_feedback", ["id"], unique=False)
	op.create_index(op.f("ix_job_recommendation_feedback_job_id"), "job_recommendation_feedback", ["job_id"], unique=False)
	op.create_index(op.f("ix_job_recommendation_feedback_user_id"), "job_recommendation_feedback", ["user_id"], unique=False)
	op.create_table(
		"content_versions",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("content_generation_id", sa.Integer(), nullable=False),
		sa.Column("version_number", sa.Integer(), nullable=False),
		sa.Column("content", sa.Text(), nullable=False),
		sa.Column("change_description", sa.String(), nullable=True),
		sa.Column("change_type", sa.String(), nullable=False),
		sa.Column("created_at", sa.DateTime(), nullable=True),
		sa.Column("created_by", sa.String(), nullable=True),
		sa.ForeignKeyConstraint(
			["content_generation_id"],
			["content_generations.id"],
		),
		sa.PrimaryKeyConstraint("id"),
	)
	op.create_index(op.f("ix_content_versions_id"), "content_versions", ["id"], unique=False)
	op.create_table(
		"interview_questions",
		sa.Column("id", sa.Integer(), nullable=False),
		sa.Column("session_id", sa.Integer(), nullable=False),
		sa.Column("question_text", sa.Text(), nullable=False),
		sa.Column("question_type", sa.String(), nullable=True),
		sa.Column("answer_text", sa.Text(), nullable=True),
		sa.Column("feedback", sa.Text(), nullable=True),
		sa.Column("score", sa.Float(), nullable=True),
		sa.Column("created_at", sa.DateTime(), nullable=True),
		sa.Column("updated_at", sa.DateTime(), nullable=True),
		sa.ForeignKeyConstraint(
			["session_id"],
			["interview_sessions.id"],
		),
		sa.PrimaryKeyConstraint("id"),
	)
	op.create_index(op.f("ix_interview_questions_created_at"), "interview_questions", ["created_at"], unique=False)
	op.create_index(op.f("ix_interview_questions_id"), "interview_questions", ["id"], unique=False)
	op.create_index(op.f("ix_interview_questions_session_id"), "interview_questions", ["session_id"], unique=False)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_index(op.f("ix_interview_questions_session_id"), table_name="interview_questions")
	op.drop_index(op.f("ix_interview_questions_id"), table_name="interview_questions")
	op.drop_index(op.f("ix_interview_questions_created_at"), table_name="interview_questions")
	op.drop_table("interview_questions")
	op.drop_index(op.f("ix_content_versions_id"), table_name="content_versions")
	op.drop_table("content_versions")
	op.drop_index(op.f("ix_job_recommendation_feedback_user_id"), table_name="job_recommendation_feedback")
	op.drop_index(op.f("ix_job_recommendation_feedback_job_id"), table_name="job_recommendation_feedback")
	op.drop_index(op.f("ix_job_recommendation_feedback_id"), table_name="job_recommendation_feedback")
	op.drop_index(op.f("ix_job_recommendation_feedback_created_at"), table_name="job_recommendation_feedback")
	op.drop_table("job_recommendation_feedback")
	op.drop_index(op.f("ix_interview_sessions_user_id"), table_name="interview_sessions")
	op.drop_index(op.f("ix_interview_sessions_status"), table_name="interview_sessions")
	op.drop_index(op.f("ix_interview_sessions_job_id"), table_name="interview_sessions")
	op.drop_index(op.f("ix_interview_sessions_id"), table_name="interview_sessions")
	op.drop_index(op.f("ix_interview_sessions_created_at"), table_name="interview_sessions")
	op.drop_table("interview_sessions")
	op.drop_index(op.f("ix_feedback_votes_user_id"), table_name="feedback_votes")
	op.drop_index(op.f("ix_feedback_votes_id"), table_name="feedback_votes")
	op.drop_index(op.f("ix_feedback_votes_feedback_id"), table_name="feedback_votes")
	op.drop_table("feedback_votes")
	op.drop_index(op.f("ix_content_generations_id"), table_name="content_generations")
	op.drop_table("content_generations")
	op.drop_index(op.f("ix_applications_user_id"), table_name="applications")
	op.drop_index(op.f("ix_applications_status"), table_name="applications")
	op.drop_index(op.f("ix_applications_job_id"), table_name="applications")
	op.drop_index(op.f("ix_applications_id"), table_name="applications")
	op.drop_index(op.f("ix_applications_created_at"), table_name="applications")
	op.drop_table("applications")
	op.drop_index(op.f("ix_user_job_preferences_user_id"), table_name="user_job_preferences")
	op.drop_index(op.f("ix_user_job_preferences_id"), table_name="user_job_preferences")
	op.drop_table("user_job_preferences")
	op.drop_index(op.f("ix_resume_uploads_id"), table_name="resume_uploads")
	op.drop_table("resume_uploads")
	op.drop_index(op.f("ix_onboarding_progress_user_id"), table_name="onboarding_progress")
	op.drop_index(op.f("ix_onboarding_progress_id"), table_name="onboarding_progress")
	op.drop_table("onboarding_progress")
	op.drop_index(op.f("ix_jobs_user_id"), table_name="jobs")
	op.drop_index(op.f("ix_jobs_title"), table_name="jobs")
	op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
	op.drop_index(op.f("ix_jobs_id"), table_name="jobs")
	op.drop_index(op.f("ix_jobs_created_at"), table_name="jobs")
	op.drop_index(op.f("ix_jobs_company"), table_name="jobs")
	op.drop_table("jobs")
	op.drop_index(op.f("ix_help_article_votes_user_id"), table_name="help_article_votes")
	op.drop_index(op.f("ix_help_article_votes_id"), table_name="help_article_votes")
	op.drop_index(op.f("ix_help_article_votes_article_id"), table_name="help_article_votes")
	op.drop_table("help_article_votes")
	op.drop_index(op.f("ix_feedback_user_id"), table_name="feedback")
	op.drop_index(op.f("ix_feedback_type"), table_name="feedback")
	op.drop_index(op.f("ix_feedback_status"), table_name="feedback")
	op.drop_index(op.f("ix_feedback_id"), table_name="feedback")
	op.drop_index(op.f("ix_feedback_created_at"), table_name="feedback")
	op.drop_table("feedback")
	op.drop_table("agent_executions")
	op.drop_index(op.f("ix_users_username"), table_name="users")
	op.drop_index(op.f("ix_users_id"), table_name="users")
	op.drop_index(op.f("ix_users_email"), table_name="users")
	op.drop_table("users")
	op.drop_index(op.f("ix_help_articles_slug"), table_name="help_articles")
	op.drop_index(op.f("ix_help_articles_is_published"), table_name="help_articles")
	op.drop_index(op.f("ix_help_articles_id"), table_name="help_articles")
	op.drop_index(op.f("ix_help_articles_created_at"), table_name="help_articles")
	op.drop_index(op.f("ix_help_articles_category"), table_name="help_articles")
	op.drop_table("help_articles")
	op.drop_table("contract_analyses")
	op.drop_index(op.f("ix_analytics_user_id"), table_name="analytics")
	op.drop_index(op.f("ix_analytics_type"), table_name="analytics")
	op.drop_index(op.f("ix_analytics_id"), table_name="analytics")
	op.drop_table("analytics")
	op.drop_table("analysis_history")
	# ### end Alembic commands ###
