"""sync schema with models: add missing relationships, constraints, and tables

Revision ID: 32b030e445af
Revises: 4af80d1f6e6a
Create Date: 2025-11-09 01:12:55.728059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32b030e445af'
down_revision: Union[str, Sequence[str], None] = '4af80d1f6e6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if tables/indexes exist before dropping
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()

    if 'apscheduler_jobs' in existing_tables:
        # Check for index before dropping
        indexes = [i['name'] for i in inspector.get_indexes('apscheduler_jobs')]
        if 'ix_apscheduler_jobs_next_run_time' in indexes:
            op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
        op.drop_table('apscheduler_jobs')

    # Check jobs indexes
    if 'jobs' in existing_tables:
        job_indexes = [i['name'] for i in inspector.get_indexes('jobs')]
        if 'ix_jobs_application_url' in job_indexes:
            op.drop_index(op.f('ix_jobs_application_url'), table_name='jobs')
        if 'ix_jobs_user_company_title_location' in job_indexes:
            op.drop_index(op.f('ix_jobs_user_company_title_location'), table_name='jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_jobs_user_company_title_location'), 'jobs', ['user_id', 'company', 'title', 'location'], unique=False)
    op.create_index(op.f('ix_jobs_application_url'), 'jobs', ['application_url'], unique=False)
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('apscheduler_jobs_pkey'))
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
