"""Add currency to Job model and rename link to application_url

Revision ID: a8a21a47e7a6
Revises: 7eb1dbf5d90a
Create Date: 2025-10-23 21:58:48.642701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8a21a47e7a6'
down_revision: Union[str, Sequence[str], None] = '7eb1dbf5d90a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('application_url', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('currency', sa.String(), nullable=True))
    op.drop_column('jobs', 'link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('link', sa.VARCHAR(), nullable=True))
    op.drop_column('jobs', 'currency')
    op.drop_column('jobs', 'application_url')
    # ### end Alembic commands ###
