"""Add interview_feedback to Application

Revision ID: e98860839e32
Revises: 86e771869702
Create Date: 2025-10-22 18:51:32.822625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e98860839e32'
down_revision: Union[str, Sequence[str], None] = '86e771869702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('interview_feedback', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'interview_feedback')
    # ### end Alembic commands ###
