"""Pydantic schemas"""

from .user import UserCreate, UserLogin, UserResponse
from .job import JobCreate, JobUpdate, JobResponse
from .application import ApplicationCreate, ApplicationUpdate, ApplicationResponse
from .job_recommendation_feedback import (
	JobRecommendationFeedbackCreate,
	JobRecommendationFeedbackUpdate,
	JobRecommendationFeedbackResponse,
	JobRecommendationFeedbackSummary,
	FeedbackAnalytics,
	BulkFeedbackCreate,
)
from .interview import (
	InterviewSessionCreate,
	InterviewSessionUpdate,
	InterviewSessionResponse,
	InterviewQuestionCreate,
	InterviewQuestionUpdate,
	InterviewQuestionResponse,
)
from .notification import (
	NotificationCreate,
	NotificationUpdate,
	NotificationResponse,
	NotificationListResponse,
	NotificationMarkReadRequest,
	NotificationBulkDeleteRequest,
	NotificationPreferencesCreate,
	NotificationPreferencesUpdate,
	NotificationPreferencesResponse,
	NotificationStatistics,
	JobStatusChangeNotification,
	ApplicationUpdateNotification,
	InterviewReminderNotification,
	NewJobMatchNotification,
)

__all__ = [
	"ApplicationCreate",
	"ApplicationResponse",
	"ApplicationUpdate",
	"ApplicationUpdateNotification",
	"BulkFeedbackCreate",
	"FeedbackAnalytics",
	"InterviewQuestionCreate",
	"InterviewQuestionResponse",
	"InterviewQuestionUpdate",
	"InterviewReminderNotification",
	"InterviewSessionCreate",
	"InterviewSessionResponse",
	"InterviewSessionUpdate",
	"JobCreate",
	"JobRecommendationFeedbackCreate",
	"JobRecommendationFeedbackResponse",
	"JobRecommendationFeedbackSummary",
	"JobRecommendationFeedbackUpdate",
	"JobResponse",
	"JobStatusChangeNotification",
	"JobUpdate",
	"NewJobMatchNotification",
	"NotificationBulkDeleteRequest",
	"NotificationCreate",
	"NotificationListResponse",
	"NotificationMarkReadRequest",
	"NotificationPreferencesCreate",
	"NotificationPreferencesResponse",
	"NotificationPreferencesUpdate",
	"NotificationResponse",
	"NotificationStatistics",
	"NotificationUpdate",
	"UserCreate",
	"UserLogin",
	"UserResponse",
]
