# Codecov Configuration
# https://docs.codecov.com/docs/codecov-yaml

# Coverage targets
coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80% # Target coverage for entire project
        threshold: 2% # Allow 2% drop without failing
        if_ci_failed: error # Fail if CI fails

    patch:
      default:
        target: 70% # New code should have 70% coverage
        threshold: 5%
        if_ci_failed: error

    changes:
      default:
        if_ci_failed: error

# Comment settings
comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false # Always post comment
  require_base: false
  require_head: true

# Files to ignore
ignore:
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  - "**/*.stories.tsx"
  - "**/node_modules/**"
  - "**/.next/**"
  - "**/coverage/**"
  - "**/dist/**"
  - "**/__tests__/**"
  - "**/__mocks__/**"
  - "**/tests/**"
  - "**/*.config.js"
  - "**/*.config.ts"
  - "**/next.config.js"
  - "**/jest.config.js"
  - "**/playwright.config.ts"
  - "**/postcss.config.mjs"
  - "**/tailwind.config.ts"

# Flags for different parts of the codebase
flags:
  frontend:
    paths:
      - "frontend/src/"
    carryforward: true

  components:
    paths:
      - "frontend/src/components/"
    carryforward: true

  features:
    paths:
      - "frontend/src/features/"
    carryforward: true

  pages:
    paths:
      - "frontend/src/app/"
    carryforward: true

# Pull request comments
github_checks:
  annotations: true

# Codecov UI settings
codecov:
  require_ci_to_pass: true
  notify:
    after_n_builds: 1
    wait_for_ci: true
